// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeysqo_4oBVWTtoLB2cUFAy43XBSxP5YU',
    appId: '1:710874112123:web:7659f8b94f36f23ecd02de',
    messagingSenderId: '710874112123',
    projectId: 'flutter-chat-app-2a6c8',
    authDomain: 'flutter-chat-app-2a6c8.firebaseapp.com',
    storageBucket: 'flutter-chat-app-2a6c8.appspot.com',
    measurementId: 'G-341QEHLRL9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1g4z4vDYsSuSWwNH0vyfgos9rP7haEMY',
    appId: '1:710874112123:android:b230147f2105c738cd02de',
    messagingSenderId: '710874112123',
    projectId: 'flutter-chat-app-2a6c8',
    storageBucket: 'flutter-chat-app-2a6c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOEjcFN0h65JI5NjrscWcdsx3JWwECQ2g',
    appId: '1:710874112123:ios:400f00cac24fe0afcd02de',
    messagingSenderId: '710874112123',
    projectId: 'flutter-chat-app-2a6c8',
    storageBucket: 'flutter-chat-app-2a6c8.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOEjcFN0h65JI5NjrscWcdsx3JWwECQ2g',
    appId: '1:710874112123:ios:400f00cac24fe0afcd02de',
    messagingSenderId: '710874112123',
    projectId: 'flutter-chat-app-2a6c8',
    storageBucket: 'flutter-chat-app-2a6c8.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeysqo_4oBVWTtoLB2cUFAy43XBSxP5YU',
    appId: '1:710874112123:web:29a59ce4546c32a8cd02de',
    messagingSenderId: '710874112123',
    projectId: 'flutter-chat-app-2a6c8',
    authDomain: 'flutter-chat-app-2a6c8.firebaseapp.com',
    storageBucket: 'flutter-chat-app-2a6c8.appspot.com',
    measurementId: 'G-WX49ZBF2SW',
  );

}